# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import asdp_pb2 as asdp__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in asdp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentDataPlaneServiceStub(object):
    """AgentDataPlaneService is the ASDP gRPC service.
    Single bidirectional stream multiplexing all message types (analogous to xDS ADS).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/agentscope.protocol.v1.AgentDataPlaneService/Connect',
                request_serializer=asdp__pb2.Upstream.SerializeToString,
                response_deserializer=asdp__pb2.Downstream.FromString,
                _registered_method=True)


class AgentDataPlaneServiceServicer(object):
    """AgentDataPlaneService is the ASDP gRPC service.
    Single bidirectional stream multiplexing all message types (analogous to xDS ADS).
    """

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentDataPlaneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=asdp__pb2.Upstream.FromString,
                    response_serializer=asdp__pb2.Downstream.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentscope.protocol.v1.AgentDataPlaneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentscope.protocol.v1.AgentDataPlaneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentDataPlaneService(object):
    """AgentDataPlaneService is the ASDP gRPC service.
    Single bidirectional stream multiplexing all message types (analogous to xDS ADS).
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/agentscope.protocol.v1.AgentDataPlaneService/Connect',
            asdp__pb2.Upstream.SerializeToString,
            asdp__pb2.Downstream.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
