// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/asdp/asdp.proto

package asdp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigType identifies the type of configuration resource (analogous to xDS type_url).
type ConfigType int32

const (
	ConfigType_CONFIG_TYPE_UNSPECIFIED ConfigType = 0
	ConfigType_CONFIG_TYPE_AGENT       ConfigType = 1
	ConfigType_CONFIG_TYPE_TOOL        ConfigType = 2
	ConfigType_CONFIG_TYPE_SKILL       ConfigType = 3
	ConfigType_CONFIG_TYPE_OVERRIDE    ConfigType = 4
	ConfigType_CONFIG_TYPE_MODEL       ConfigType = 5
)

// Enum value maps for ConfigType.
var (
	ConfigType_name = map[int32]string{
		0: "CONFIG_TYPE_UNSPECIFIED",
		1: "CONFIG_TYPE_AGENT",
		2: "CONFIG_TYPE_TOOL",
		3: "CONFIG_TYPE_SKILL",
		4: "CONFIG_TYPE_OVERRIDE",
		5: "CONFIG_TYPE_MODEL",
	}
	ConfigType_value = map[string]int32{
		"CONFIG_TYPE_UNSPECIFIED": 0,
		"CONFIG_TYPE_AGENT":       1,
		"CONFIG_TYPE_TOOL":        2,
		"CONFIG_TYPE_SKILL":       3,
		"CONFIG_TYPE_OVERRIDE":    4,
		"CONFIG_TYPE_MODEL":       5,
	}
)

func (x ConfigType) Enum() *ConfigType {
	p := new(ConfigType)
	*p = x
	return p
}

func (x ConfigType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_asdp_asdp_proto_enumTypes[0].Descriptor()
}

func (ConfigType) Type() protoreflect.EnumType {
	return &file_internal_asdp_asdp_proto_enumTypes[0]
}

func (x ConfigType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigType.Descriptor instead.
func (ConfigType) EnumDescriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{0}
}

type Upstream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *UpstreamMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Upstream_Connect
	//	*Upstream_ConfigAck
	//	*Upstream_SessionReport
	//	*Upstream_ExecutionAttempt
	//	*Upstream_Heartbeat
	//	*Upstream_EventReport
	//	*Upstream_ContextReport
	//	*Upstream_Inventory
	//	*Upstream_ConversationTurn
	Payload       isUpstream_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upstream) Reset() {
	*x = Upstream{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upstream) ProtoMessage() {}

func (x *Upstream) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upstream.ProtoReflect.Descriptor instead.
func (*Upstream) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{0}
}

func (x *Upstream) GetMeta() *UpstreamMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Upstream) GetPayload() isUpstream_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Upstream) GetConnect() *ConnectRequest {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *Upstream) GetConfigAck() *ConfigAck {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_ConfigAck); ok {
			return x.ConfigAck
		}
	}
	return nil
}

func (x *Upstream) GetSessionReport() *SessionReport {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_SessionReport); ok {
			return x.SessionReport
		}
	}
	return nil
}

func (x *Upstream) GetExecutionAttempt() *ExecutionAttemptReport {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_ExecutionAttempt); ok {
			return x.ExecutionAttempt
		}
	}
	return nil
}

func (x *Upstream) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Upstream) GetEventReport() *EventReport {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_EventReport); ok {
			return x.EventReport
		}
	}
	return nil
}

func (x *Upstream) GetContextReport() *ContextReport {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_ContextReport); ok {
			return x.ContextReport
		}
	}
	return nil
}

func (x *Upstream) GetInventory() *InventoryReport {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_Inventory); ok {
			return x.Inventory
		}
	}
	return nil
}

func (x *Upstream) GetConversationTurn() *ConversationTurnReport {
	if x != nil {
		if x, ok := x.Payload.(*Upstream_ConversationTurn); ok {
			return x.ConversationTurn
		}
	}
	return nil
}

type isUpstream_Payload interface {
	isUpstream_Payload()
}

type Upstream_Connect struct {
	Connect *ConnectRequest `protobuf:"bytes,10,opt,name=connect,proto3,oneof"`
}

type Upstream_ConfigAck struct {
	ConfigAck *ConfigAck `protobuf:"bytes,11,opt,name=config_ack,json=configAck,proto3,oneof"`
}

type Upstream_SessionReport struct {
	SessionReport *SessionReport `protobuf:"bytes,12,opt,name=session_report,json=sessionReport,proto3,oneof"`
}

type Upstream_ExecutionAttempt struct {
	ExecutionAttempt *ExecutionAttemptReport `protobuf:"bytes,13,opt,name=execution_attempt,json=executionAttempt,proto3,oneof"`
}

type Upstream_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,14,opt,name=heartbeat,proto3,oneof"`
}

type Upstream_EventReport struct {
	EventReport *EventReport `protobuf:"bytes,15,opt,name=event_report,json=eventReport,proto3,oneof"` // Level 2 event stream
}

type Upstream_ContextReport struct {
	ContextReport *ContextReport `protobuf:"bytes,16,opt,name=context_report,json=contextReport,proto3,oneof"` // Level 4 effective context
}

type Upstream_Inventory struct {
	Inventory *InventoryReport `protobuf:"bytes,17,opt,name=inventory,proto3,oneof"` // instance inventory (subagents / workspaces / health)
}

type Upstream_ConversationTurn struct {
	ConversationTurn *ConversationTurnReport `protobuf:"bytes,18,opt,name=conversation_turn,json=conversationTurn,proto3,oneof"`
}

func (*Upstream_Connect) isUpstream_Payload() {}

func (*Upstream_ConfigAck) isUpstream_Payload() {}

func (*Upstream_SessionReport) isUpstream_Payload() {}

func (*Upstream_ExecutionAttempt) isUpstream_Payload() {}

func (*Upstream_Heartbeat) isUpstream_Payload() {}

func (*Upstream_EventReport) isUpstream_Payload() {}

func (*Upstream_ContextReport) isUpstream_Payload() {}

func (*Upstream_Inventory) isUpstream_Payload() {}

func (*Upstream_ConversationTurn) isUpstream_Payload() {}

type UpstreamMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentKey      string                 `protobuf:"bytes,1,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`
	InstanceKey   string                 `protobuf:"bytes,2,opt,name=instance_key,json=instanceKey,proto3" json:"instance_key,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tenant        string                 `protobuf:"bytes,5,opt,name=tenant,proto3" json:"tenant,omitempty"`
	AgentId       string                 `protobuf:"bytes,6,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	BindingId     string                 `protobuf:"bytes,7,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	Generation    int64                  `protobuf:"varint,8,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamMeta) Reset() {
	*x = UpstreamMeta{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamMeta) ProtoMessage() {}

func (x *UpstreamMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamMeta.ProtoReflect.Descriptor instead.
func (*UpstreamMeta) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{1}
}

func (x *UpstreamMeta) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *UpstreamMeta) GetInstanceKey() string {
	if x != nil {
		return x.InstanceKey
	}
	return ""
}

func (x *UpstreamMeta) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpstreamMeta) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UpstreamMeta) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *UpstreamMeta) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpstreamMeta) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

func (x *UpstreamMeta) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// Handshake (sent on connection establish, analogous to xDS initial DiscoveryRequest)
type ConnectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Runtime         string                 `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	SdkVersion      string                 `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	SessionAffinity string                 `protobuf:"bytes,4,opt,name=session_affinity,json=sessionAffinity,proto3" json:"session_affinity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *ConnectRequest) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *ConnectRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ConnectRequest) GetSessionAffinity() string {
	if x != nil {
		return x.SessionAffinity
	}
	return ""
}

// Config acknowledgement (analogous to xDS ACK/NACK)
type ConfigAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigType    ConfigType             `protobuf:"varint,1,opt,name=config_type,json=configType,proto3,enum=agentscope.protocol.v1.ConfigType" json:"config_type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Nonce         string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Accepted      bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason  string                 `protobuf:"bytes,5,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigAck) Reset() {
	*x = ConfigAck{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAck) ProtoMessage() {}

func (x *ConfigAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAck.ProtoReflect.Descriptor instead.
func (*ConfigAck) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigAck) GetConfigType() ConfigType {
	if x != nil {
		return x.ConfigType
	}
	return ConfigType_CONFIG_TYPE_UNSPECIFIED
}

func (x *ConfigAck) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigAck) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ConfigAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConfigAck) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

// Session state report (periodic batch, e.g. every 10s)
type SessionReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionSnapshot     `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionReport) Reset() {
	*x = SessionReport{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReport) ProtoMessage() {}

func (x *SessionReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReport.ProtoReflect.Descriptor instead.
func (*SessionReport) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{4}
}

func (x *SessionReport) GetSessions() []*SessionSnapshot {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Phase            string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	MessageCount     int32                  `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,4,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,5,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	ContextPressure  float64                `protobuf:"fixed64,6,opt,name=context_pressure,json=contextPressure,proto3" json:"context_pressure,omitempty"`
	// Framework identification (Level 1 extension, see sdk-design.md §3.1)
	Framework        string `protobuf:"bytes,10,opt,name=framework,proto3" json:"framework,omitempty"` // "claude-agent-sdk" | "langchain" | "adk" | ...
	FrameworkVersion string `protobuf:"bytes,11,opt,name=framework_version,json=frameworkVersion,proto3" json:"framework_version,omitempty"`
	// Context change detection
	ContextHash           string `protobuf:"bytes,12,opt,name=context_hash,json=contextHash,proto3" json:"context_hash,omitempty"`                                  // SHA-256 (first 16 hex) of the effective context
	IsCompacted           bool   `protobuf:"varint,13,opt,name=is_compacted,json=isCompacted,proto3" json:"is_compacted,omitempty"`                                 // whether the context has been compacted
	EffectiveMessageCount int32  `protobuf:"varint,14,opt,name=effective_message_count,json=effectiveMessageCount,proto3" json:"effective_message_count,omitempty"` // effective messages after compaction (!= message_count)
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SessionSnapshot) Reset() {
	*x = SessionSnapshot{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSnapshot) ProtoMessage() {}

func (x *SessionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSnapshot.ProtoReflect.Descriptor instead.
func (*SessionSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{5}
}

func (x *SessionSnapshot) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionSnapshot) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SessionSnapshot) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SessionSnapshot) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *SessionSnapshot) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *SessionSnapshot) GetContextPressure() float64 {
	if x != nil {
		return x.ContextPressure
	}
	return 0
}

func (x *SessionSnapshot) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *SessionSnapshot) GetFrameworkVersion() string {
	if x != nil {
		return x.FrameworkVersion
	}
	return ""
}

func (x *SessionSnapshot) GetContextHash() string {
	if x != nil {
		return x.ContextHash
	}
	return ""
}

func (x *SessionSnapshot) GetIsCompacted() bool {
	if x != nil {
		return x.IsCompacted
	}
	return false
}

func (x *SessionSnapshot) GetEffectiveMessageCount() int32 {
	if x != nil {
		return x.EffectiveMessageCount
	}
	return 0
}

// ExecutionAttemptReport is fenced by attempt identity and dispatch generation.
type ExecutionAttemptReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AttemptId      string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	AgentTaskId    string                 `protobuf:"bytes,2,opt,name=agent_task_id,json=agentTaskId,proto3" json:"agent_task_id,omitempty"`
	RunId          string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	NodeId         string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Generation     int64                  `protobuf:"varint,5,opt,name=generation,proto3" json:"generation,omitempty"`
	Action         string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"` // ack | preparing | start | heartbeat | waiting | progress | respond | complete | fail | cancelled
	InputIds       []string               `protobuf:"bytes,7,rep,name=input_ids,json=inputIds,proto3" json:"input_ids,omitempty"`
	Content        string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	Result         []byte                 `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,10,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Checkpoint     []byte                 `protobuf:"bytes,12,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	Usage          []byte                 `protobuf:"bytes,13,opt,name=usage,proto3" json:"usage,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,14,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	AttemptToken   string                 `protobuf:"bytes,15,opt,name=attempt_token,json=attemptToken,proto3" json:"attempt_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionAttemptReport) Reset() {
	*x = ExecutionAttemptReport{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionAttemptReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionAttemptReport) ProtoMessage() {}

func (x *ExecutionAttemptReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionAttemptReport.ProtoReflect.Descriptor instead.
func (*ExecutionAttemptReport) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{6}
}

func (x *ExecutionAttemptReport) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ExecutionAttemptReport) GetAgentTaskId() string {
	if x != nil {
		return x.AgentTaskId
	}
	return ""
}

func (x *ExecutionAttemptReport) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecutionAttemptReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecutionAttemptReport) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ExecutionAttemptReport) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecutionAttemptReport) GetInputIds() []string {
	if x != nil {
		return x.InputIds
	}
	return nil
}

func (x *ExecutionAttemptReport) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExecutionAttemptReport) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecutionAttemptReport) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ExecutionAttemptReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExecutionAttemptReport) GetCheckpoint() []byte {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *ExecutionAttemptReport) GetUsage() []byte {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ExecutionAttemptReport) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ExecutionAttemptReport) GetAttemptToken() string {
	if x != nil {
		return x.AttemptToken
	}
	return ""
}

// Heartbeat (bidirectional keepalive)
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Instance health reported by data plane
type InstanceHealth struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,3,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	CpuUsage       float64                `protobuf:"fixed64,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage    float64                `protobuf:"fixed64,5,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstanceHealth) Reset() {
	*x = InstanceHealth{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceHealth) ProtoMessage() {}

func (x *InstanceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceHealth.ProtoReflect.Descriptor instead.
func (*InstanceHealth) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{8}
}

func (x *InstanceHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *InstanceHealth) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InstanceHealth) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *InstanceHealth) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *InstanceHealth) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

// EventReport is the Level-2 event stream report (batched, e.g. every 5s or
// every 20 events). Written by the control plane into the session_events table.
type EventReport struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Events []*SessionEventMsg     `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// Stable across retries. The control plane acknowledges this report only
	// after every returned cursor has been durably committed.
	ReportId      string `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReport) Reset() {
	*x = EventReport{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReport) ProtoMessage() {}

func (x *EventReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReport.ProtoReflect.Descriptor instead.
func (*EventReport) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{9}
}

func (x *EventReport) GetEvents() []*SessionEventMsg {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventReport) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

// EventReportAck is the durable commit acknowledgement for an EventReport.
// A cursor is emitted only through the highest contiguous sequence committed
// for that session in this report. Missing cursors remain pending and are
// retransmitted by the data plane.
type EventReportAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Committed     []*SessionEventCursor  `protobuf:"bytes,2,rep,name=committed,proto3" json:"committed,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReportAck) Reset() {
	*x = EventReportAck{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReportAck) ProtoMessage() {}

func (x *EventReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReportAck.ProtoReflect.Descriptor instead.
func (*EventReportAck) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{10}
}

func (x *EventReportAck) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *EventReportAck) GetCommitted() []*SessionEventCursor {
	if x != nil {
		return x.Committed
	}
	return nil
}

func (x *EventReportAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SessionEventCursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CommittedSeq  int32                  `protobuf:"varint,2,opt,name=committed_seq,json=committedSeq,proto3" json:"committed_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEventCursor) Reset() {
	*x = SessionEventCursor{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEventCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEventCursor) ProtoMessage() {}

func (x *SessionEventCursor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEventCursor.ProtoReflect.Descriptor instead.
func (*SessionEventCursor) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{11}
}

func (x *SessionEventCursor) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEventCursor) GetCommittedSeq() int32 {
	if x != nil {
		return x.CommittedSeq
	}
	return 0
}

type SessionEventMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Seq           int32                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                                 // monotonically increasing per session; idempotency key
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`     // session_start | message | tool_call | tool_result | session_end | compaction
	OccurredAt    int64                  `protobuf:"varint,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // unix milliseconds
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`                                // user | assistant | system | tool
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                          // complete message/event text for durable replay
	ToolName      string                 `protobuf:"bytes,7,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolInput     []byte                 `protobuf:"bytes,8,opt,name=tool_input,json=toolInput,proto3" json:"tool_input,omitempty"` // JSON
	ToolOutput    string                 `protobuf:"bytes,9,opt,name=tool_output,json=toolOutput,proto3" json:"tool_output,omitempty"`
	TokensIn      int32                  `protobuf:"varint,10,opt,name=tokens_in,json=tokensIn,proto3" json:"tokens_in,omitempty"`
	TokensOut     int32                  `protobuf:"varint,11,opt,name=tokens_out,json=tokensOut,proto3" json:"tokens_out,omitempty"`
	DurationMs    int32                  `protobuf:"varint,12,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	FrameworkMeta []byte                 `protobuf:"bytes,13,opt,name=framework_meta,json=frameworkMeta,proto3" json:"framework_meta,omitempty"` // framework-private JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEventMsg) Reset() {
	*x = SessionEventMsg{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEventMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEventMsg) ProtoMessage() {}

func (x *SessionEventMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEventMsg.ProtoReflect.Descriptor instead.
func (*SessionEventMsg) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{12}
}

func (x *SessionEventMsg) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEventMsg) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SessionEventMsg) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SessionEventMsg) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

func (x *SessionEventMsg) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SessionEventMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SessionEventMsg) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *SessionEventMsg) GetToolInput() []byte {
	if x != nil {
		return x.ToolInput
	}
	return nil
}

func (x *SessionEventMsg) GetToolOutput() string {
	if x != nil {
		return x.ToolOutput
	}
	return ""
}

func (x *SessionEventMsg) GetTokensIn() int32 {
	if x != nil {
		return x.TokensIn
	}
	return 0
}

func (x *SessionEventMsg) GetTokensOut() int32 {
	if x != nil {
		return x.TokensOut
	}
	return 0
}

func (x *SessionEventMsg) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *SessionEventMsg) GetFrameworkMeta() []byte {
	if x != nil {
		return x.FrameworkMeta
	}
	return nil
}

// ContextReport is the Level-4 effective-context report, pushed on compaction
// or when context_hash changes (debounced). Written into context_snapshots.
type ContextReport struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ContextHash          string                 `protobuf:"bytes,2,opt,name=context_hash,json=contextHash,proto3" json:"context_hash,omitempty"`
	CapturedAt           int64                  `protobuf:"varint,3,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"` // unix milliseconds
	SystemPrompt         string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Messages             []byte                 `protobuf:"bytes,5,opt,name=messages,proto3" json:"messages,omitempty"` // JSON array of {role, content, is_compaction?}
	Tools                []byte                 `protobuf:"bytes,6,opt,name=tools,proto3" json:"tools,omitempty"`       // JSON array of ToolInfo
	IsCompacted          bool                   `protobuf:"varint,7,opt,name=is_compacted,json=isCompacted,proto3" json:"is_compacted,omitempty"`
	CompactionSummary    string                 `protobuf:"bytes,8,opt,name=compaction_summary,json=compactionSummary,proto3" json:"compaction_summary,omitempty"`
	OriginalMessageCount int32                  `protobuf:"varint,9,opt,name=original_message_count,json=originalMessageCount,proto3" json:"original_message_count,omitempty"`
	CompactedAt          int64                  `protobuf:"varint,10,opt,name=compacted_at,json=compactedAt,proto3" json:"compacted_at,omitempty"` // unix milliseconds
	TotalTokens          int32                  `protobuf:"varint,11,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	MaxTokens            int32                  `protobuf:"varint,12,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Framework            string                 `protobuf:"bytes,13,opt,name=framework,proto3" json:"framework,omitempty"`
	FrameworkState       []byte                 `protobuf:"bytes,14,opt,name=framework_state,json=frameworkState,proto3" json:"framework_state,omitempty"` // framework-private JSON (graph state, session metadata, ...)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ContextReport) Reset() {
	*x = ContextReport{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextReport) ProtoMessage() {}

func (x *ContextReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextReport.ProtoReflect.Descriptor instead.
func (*ContextReport) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{13}
}

func (x *ContextReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ContextReport) GetContextHash() string {
	if x != nil {
		return x.ContextHash
	}
	return ""
}

func (x *ContextReport) GetCapturedAt() int64 {
	if x != nil {
		return x.CapturedAt
	}
	return 0
}

func (x *ContextReport) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ContextReport) GetMessages() []byte {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ContextReport) GetTools() []byte {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ContextReport) GetIsCompacted() bool {
	if x != nil {
		return x.IsCompacted
	}
	return false
}

func (x *ContextReport) GetCompactionSummary() string {
	if x != nil {
		return x.CompactionSummary
	}
	return ""
}

func (x *ContextReport) GetOriginalMessageCount() int32 {
	if x != nil {
		return x.OriginalMessageCount
	}
	return 0
}

func (x *ContextReport) GetCompactedAt() int64 {
	if x != nil {
		return x.CompactedAt
	}
	return 0
}

func (x *ContextReport) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ContextReport) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ContextReport) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *ContextReport) GetFrameworkState() []byte {
	if x != nil {
		return x.FrameworkState
	}
	return nil
}

// InventoryReport carries the instance-level runtime inventory: subagents,
// workspaces and health. Sent right after connect, then on change or at the
// Level-1 cadence.
type InventoryReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subagents     []*SubagentInfo        `protobuf:"bytes,1,rep,name=subagents,proto3" json:"subagents,omitempty"`
	Workspaces    []*WorkspaceInfo       `protobuf:"bytes,2,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	Health        *InstanceHealth        `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReport) Reset() {
	*x = InventoryReport{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReport) ProtoMessage() {}

func (x *InventoryReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReport.ProtoReflect.Descriptor instead.
func (*InventoryReport) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{14}
}

func (x *InventoryReport) GetSubagents() []*SubagentInfo {
	if x != nil {
		return x.Subagents
	}
	return nil
}

func (x *InventoryReport) GetWorkspaces() []*WorkspaceInfo {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *InventoryReport) GetHealth() *InstanceHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

type SubagentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tools         []string               `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	WorkspaceMode string                 `protobuf:"bytes,4,opt,name=workspace_mode,json=workspaceMode,proto3" json:"workspace_mode,omitempty"` // isolated | shared
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`                                          // remote subagent endpoint, if any
	InvokeCount   int64                  `protobuf:"varint,6,opt,name=invoke_count,json=invokeCount,proto3" json:"invoke_count,omitempty"`
	LastInvokedAt int64                  `protobuf:"varint,7,opt,name=last_invoked_at,json=lastInvokedAt,proto3" json:"last_invoked_at,omitempty"` // unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubagentInfo) Reset() {
	*x = SubagentInfo{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubagentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubagentInfo) ProtoMessage() {}

func (x *SubagentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubagentInfo.ProtoReflect.Descriptor instead.
func (*SubagentInfo) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{15}
}

func (x *SubagentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubagentInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SubagentInfo) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *SubagentInfo) GetWorkspaceMode() string {
	if x != nil {
		return x.WorkspaceMode
	}
	return ""
}

func (x *SubagentInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SubagentInfo) GetInvokeCount() int64 {
	if x != nil {
		return x.InvokeCount
	}
	return 0
}

func (x *SubagentInfo) GetLastInvokedAt() int64 {
	if x != nil {
		return x.LastInvokedAt
	}
	return 0
}

type WorkspaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // isolated | shared | readonly
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	OwnerRef      string                 `protobuf:"bytes,4,opt,name=owner_ref,json=ownerRef,proto3" json:"owner_ref,omitempty"` // session_id or subagent name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceInfo) Reset() {
	*x = WorkspaceInfo{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceInfo) ProtoMessage() {}

func (x *WorkspaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceInfo.ProtoReflect.Descriptor instead.
func (*WorkspaceInfo) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{16}
}

func (x *WorkspaceInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WorkspaceInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *WorkspaceInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *WorkspaceInfo) GetOwnerRef() string {
	if x != nil {
		return x.OwnerRef
	}
	return ""
}

type Downstream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Downstream_ConnectAck
	//	*Downstream_ConfigPush
	//	*Downstream_SessionCmd
	//	*Downstream_ExecutionAttempt
	//	*Downstream_Heartbeat
	//	*Downstream_ConversationTurn
	//	*Downstream_EventAck
	Payload       isDownstream_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Downstream) Reset() {
	*x = Downstream{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Downstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Downstream) ProtoMessage() {}

func (x *Downstream) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Downstream.ProtoReflect.Descriptor instead.
func (*Downstream) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{17}
}

func (x *Downstream) GetPayload() isDownstream_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Downstream) GetConnectAck() *ConnectResponse {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_ConnectAck); ok {
			return x.ConnectAck
		}
	}
	return nil
}

func (x *Downstream) GetConfigPush() *ConfigPush {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_ConfigPush); ok {
			return x.ConfigPush
		}
	}
	return nil
}

func (x *Downstream) GetSessionCmd() *SessionCommand {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_SessionCmd); ok {
			return x.SessionCmd
		}
	}
	return nil
}

func (x *Downstream) GetExecutionAttempt() *ExecutionAttemptCommand {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_ExecutionAttempt); ok {
			return x.ExecutionAttempt
		}
	}
	return nil
}

func (x *Downstream) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Downstream) GetConversationTurn() *ConversationTurnCommand {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_ConversationTurn); ok {
			return x.ConversationTurn
		}
	}
	return nil
}

func (x *Downstream) GetEventAck() *EventReportAck {
	if x != nil {
		if x, ok := x.Payload.(*Downstream_EventAck); ok {
			return x.EventAck
		}
	}
	return nil
}

type isDownstream_Payload interface {
	isDownstream_Payload()
}

type Downstream_ConnectAck struct {
	ConnectAck *ConnectResponse `protobuf:"bytes,10,opt,name=connect_ack,json=connectAck,proto3,oneof"`
}

type Downstream_ConfigPush struct {
	ConfigPush *ConfigPush `protobuf:"bytes,11,opt,name=config_push,json=configPush,proto3,oneof"`
}

type Downstream_SessionCmd struct {
	SessionCmd *SessionCommand `protobuf:"bytes,12,opt,name=session_cmd,json=sessionCmd,proto3,oneof"`
}

type Downstream_ExecutionAttempt struct {
	ExecutionAttempt *ExecutionAttemptCommand `protobuf:"bytes,13,opt,name=execution_attempt,json=executionAttempt,proto3,oneof"`
}

type Downstream_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,14,opt,name=heartbeat,proto3,oneof"`
}

type Downstream_ConversationTurn struct {
	ConversationTurn *ConversationTurnCommand `protobuf:"bytes,15,opt,name=conversation_turn,json=conversationTurn,proto3,oneof"`
}

type Downstream_EventAck struct {
	EventAck *EventReportAck `protobuf:"bytes,16,opt,name=event_ack,json=eventAck,proto3,oneof"`
}

func (*Downstream_ConnectAck) isDownstream_Payload() {}

func (*Downstream_ConfigPush) isDownstream_Payload() {}

func (*Downstream_SessionCmd) isDownstream_Payload() {}

func (*Downstream_ExecutionAttempt) isDownstream_Payload() {}

func (*Downstream_Heartbeat) isDownstream_Payload() {}

func (*Downstream_ConversationTurn) isDownstream_Payload() {}

func (*Downstream_EventAck) isDownstream_Payload() {}

type ConnectResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Accepted            bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason        string                 `protobuf:"bytes,2,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	ControlPlaneVersion string                 `protobuf:"bytes,3,opt,name=control_plane_version,json=controlPlaneVersion,proto3" json:"control_plane_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{18}
}

func (x *ConnectResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConnectResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *ConnectResponse) GetControlPlaneVersion() string {
	if x != nil {
		return x.ControlPlaneVersion
	}
	return ""
}

// Config push (analogous to xDS DiscoveryResponse)
type ConfigPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigType    ConfigType             `protobuf:"varint,1,opt,name=config_type,json=configType,proto3,enum=agentscope.protocol.v1.ConfigType" json:"config_type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Resources     []byte                 `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	Nonce         string                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPush) Reset() {
	*x = ConfigPush{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPush) ProtoMessage() {}

func (x *ConfigPush) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPush.ProtoReflect.Descriptor instead.
func (*ConfigPush) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{19}
}

func (x *ConfigPush) GetConfigType() ConfigType {
	if x != nil {
		return x.ConfigType
	}
	return ConfigType_CONFIG_TYPE_UNSPECIFIED
}

func (x *ConfigPush) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigPush) GetResources() []byte {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ConfigPush) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

// SessionCommand is a control-plane → data-plane session instruction.
// `command` is a string (not an enum) so new verbs can be added without
// breaking wire compatibility. Known values and HTTP parity
// (see docs/zh/controlplane/contract.md):
//
//	compress   ↔ POST /agentscope/sessions/{id}/compress   (capability: session-command)
//	terminate  ↔ POST /agentscope/sessions/{id}/terminate  (capability: session-command)
//	abort      ↔ POST /agentscope/sessions/{id}/abort      (capability: session-abort)
//	undo       ↔ POST /agentscope/sessions/{id}/undo       (capability: session-undo, optional)
//	redo       ↔ POST /agentscope/sessions/{id}/redo       (capability: session-redo, optional)
//
// Success / error semantics match the HTTP Command contract
// (accepted/commandId/phase/result；501 unsupported, 409 busy/wait_idle,
// 404 not_found, 503 unreachable on CP, 500 failed).
type SessionCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"` // compress | terminate | abort | undo | redo | ...
	Params        []byte                 `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCommand) Reset() {
	*x = SessionCommand{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCommand) ProtoMessage() {}

func (x *SessionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCommand.ProtoReflect.Descriptor instead.
func (*SessionCommand) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{20}
}

func (x *SessionCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SessionCommand) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

// ConversationTurnCommand is the explicit online invocation protocol. It is
// separate from SessionCommand because user turns require public invocation
// identity, fencing, acknowledgement, streaming, and a final result.
type ConversationTurnCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InvocationId   string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	TurnId         string                 `protobuf:"bytes,3,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	BindingId      string                 `protobuf:"bytes,6,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	InstanceId     string                 `protobuf:"bytes,7,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Generation     int64                  `protobuf:"varint,8,opt,name=generation,proto3" json:"generation,omitempty"`
	Input          []byte                 `protobuf:"bytes,9,opt,name=input,proto3" json:"input,omitempty"`
	Deadline       int64                  `protobuf:"varint,10,opt,name=deadline,proto3" json:"deadline,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,11,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationTurnCommand) Reset() {
	*x = ConversationTurnCommand{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationTurnCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationTurnCommand) ProtoMessage() {}

func (x *ConversationTurnCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationTurnCommand.ProtoReflect.Descriptor instead.
func (*ConversationTurnCommand) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{21}
}

func (x *ConversationTurnCommand) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *ConversationTurnCommand) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationTurnCommand) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *ConversationTurnCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConversationTurnCommand) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ConversationTurnCommand) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

func (x *ConversationTurnCommand) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ConversationTurnCommand) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ConversationTurnCommand) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ConversationTurnCommand) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *ConversationTurnCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ConversationTurnReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InvocationId   string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	TurnId         string                 `protobuf:"bytes,3,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Generation     int64                  `protobuf:"varint,5,opt,name=generation,proto3" json:"generation,omitempty"`
	Action         string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"` // accepted | started | delta | completed | failed | cancelled
	Sequence       int64                  `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Payload        []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,9,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationTurnReport) Reset() {
	*x = ConversationTurnReport{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationTurnReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationTurnReport) ProtoMessage() {}

func (x *ConversationTurnReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationTurnReport.ProtoReflect.Descriptor instead.
func (*ConversationTurnReport) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{22}
}

func (x *ConversationTurnReport) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *ConversationTurnReport) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationTurnReport) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *ConversationTurnReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConversationTurnReport) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ConversationTurnReport) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ConversationTurnReport) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ConversationTurnReport) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConversationTurnReport) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ConversationTurnReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ExecutionAttemptCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AttemptId      string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	AgentTaskId    string                 `protobuf:"bytes,2,opt,name=agent_task_id,json=agentTaskId,proto3" json:"agent_task_id,omitempty"`
	RunId          string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	NodeId         string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Generation     int64                  `protobuf:"varint,5,opt,name=generation,proto3" json:"generation,omitempty"`
	Command        string                 `protobuf:"bytes,6,opt,name=command,proto3" json:"command,omitempty"` // dispatch | cancel
	ContextUrl     string                 `protobuf:"bytes,7,opt,name=context_url,json=contextUrl,proto3" json:"context_url,omitempty"`
	TaskToken      string                 `protobuf:"bytes,8,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	AttemptToken   string                 `protobuf:"bytes,9,opt,name=attempt_token,json=attemptToken,proto3" json:"attempt_token,omitempty"`
	RuntimeBinding []byte                 `protobuf:"bytes,10,opt,name=runtime_binding,json=runtimeBinding,proto3" json:"runtime_binding,omitempty"`
	Payload        []byte                 `protobuf:"bytes,11,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp      int64                  `protobuf:"varint,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionAttemptCommand) Reset() {
	*x = ExecutionAttemptCommand{}
	mi := &file_internal_asdp_asdp_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionAttemptCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionAttemptCommand) ProtoMessage() {}

func (x *ExecutionAttemptCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_asdp_asdp_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionAttemptCommand.ProtoReflect.Descriptor instead.
func (*ExecutionAttemptCommand) Descriptor() ([]byte, []int) {
	return file_internal_asdp_asdp_proto_rawDescGZIP(), []int{23}
}

func (x *ExecutionAttemptCommand) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ExecutionAttemptCommand) GetAgentTaskId() string {
	if x != nil {
		return x.AgentTaskId
	}
	return ""
}

func (x *ExecutionAttemptCommand) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecutionAttemptCommand) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecutionAttemptCommand) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ExecutionAttemptCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecutionAttemptCommand) GetContextUrl() string {
	if x != nil {
		return x.ContextUrl
	}
	return ""
}

func (x *ExecutionAttemptCommand) GetTaskToken() string {
	if x != nil {
		return x.TaskToken
	}
	return ""
}

func (x *ExecutionAttemptCommand) GetAttemptToken() string {
	if x != nil {
		return x.AttemptToken
	}
	return ""
}

func (x *ExecutionAttemptCommand) GetRuntimeBinding() []byte {
	if x != nil {
		return x.RuntimeBinding
	}
	return nil
}

func (x *ExecutionAttemptCommand) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecutionAttemptCommand) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_internal_asdp_asdp_proto protoreflect.FileDescriptor

const file_internal_asdp_asdp_proto_rawDesc = "" +
	"\n" +
	"\x18internal/asdp/asdp.proto\x12\x16agentscope.protocol.v1\"\x8b\x06\n" +
	"\bUpstream\x128\n" +
	"\x04meta\x18\x01 \x01(\v2$.agentscope.protocol.v1.UpstreamMetaR\x04meta\x12B\n" +
	"\aconnect\x18\n" +
	" \x01(\v2&.agentscope.protocol.v1.ConnectRequestH\x00R\aconnect\x12B\n" +
	"\n" +
	"config_ack\x18\v \x01(\v2!.agentscope.protocol.v1.ConfigAckH\x00R\tconfigAck\x12N\n" +
	"\x0esession_report\x18\f \x01(\v2%.agentscope.protocol.v1.SessionReportH\x00R\rsessionReport\x12]\n" +
	"\x11execution_attempt\x18\r \x01(\v2..agentscope.protocol.v1.ExecutionAttemptReportH\x00R\x10executionAttempt\x12A\n" +
	"\theartbeat\x18\x0e \x01(\v2!.agentscope.protocol.v1.HeartbeatH\x00R\theartbeat\x12H\n" +
	"\fevent_report\x18\x0f \x01(\v2#.agentscope.protocol.v1.EventReportH\x00R\veventReport\x12N\n" +
	"\x0econtext_report\x18\x10 \x01(\v2%.agentscope.protocol.v1.ContextReportH\x00R\rcontextReport\x12G\n" +
	"\tinventory\x18\x11 \x01(\v2'.agentscope.protocol.v1.InventoryReportH\x00R\tinventory\x12]\n" +
	"\x11conversation_turn\x18\x12 \x01(\v2..agentscope.protocol.v1.ConversationTurnReportH\x00R\x10conversationTurnB\t\n" +
	"\apayload\"\xfc\x01\n" +
	"\fUpstreamMeta\x12\x1b\n" +
	"\tagent_key\x18\x01 \x01(\tR\bagentKey\x12!\n" +
	"\finstance_key\x18\x02 \x01(\tR\vinstanceKey\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06tenant\x18\x05 \x01(\tR\x06tenant\x12\x19\n" +
	"\bagent_id\x18\x06 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"binding_id\x18\a \x01(\tR\tbindingId\x12\x1e\n" +
	"\n" +
	"generation\x18\b \x01(\x03R\n" +
	"generation\"\x9a\x01\n" +
	"\x0eConnectRequest\x12\x18\n" +
	"\aruntime\x18\x01 \x01(\tR\aruntime\x12\x1f\n" +
	"\vsdk_version\x18\x02 \x01(\tR\n" +
	"sdkVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12)\n" +
	"\x10session_affinity\x18\x04 \x01(\tR\x0fsessionAffinity\"\xc1\x01\n" +
	"\tConfigAck\x12C\n" +
	"\vconfig_type\x18\x01 \x01(\x0e2\".agentscope.protocol.v1.ConfigTypeR\n" +
	"configType\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x05 \x01(\tR\frejectReason\"T\n" +
	"\rSessionReport\x12C\n" +
	"\bsessions\x18\x01 \x03(\v2'.agentscope.protocol.v1.SessionSnapshotR\bsessions\"\xb1\x03\n" +
	"\x0fSessionSnapshot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x05R\fmessageCount\x12#\n" +
	"\rprompt_tokens\x18\x04 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x05 \x01(\x03R\x10completionTokens\x12)\n" +
	"\x10context_pressure\x18\x06 \x01(\x01R\x0fcontextPressure\x12\x1c\n" +
	"\tframework\x18\n" +
	" \x01(\tR\tframework\x12+\n" +
	"\x11framework_version\x18\v \x01(\tR\x10frameworkVersion\x12!\n" +
	"\fcontext_hash\x18\f \x01(\tR\vcontextHash\x12!\n" +
	"\fis_compacted\x18\r \x01(\bR\visCompacted\x126\n" +
	"\x17effective_message_count\x18\x0e \x01(\x05R\x15effectiveMessageCount\"\xda\x03\n" +
	"\x16ExecutionAttemptReport\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\"\n" +
	"\ragent_task_id\x18\x02 \x01(\tR\vagentTaskId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x1e\n" +
	"\n" +
	"generation\x18\x05 \x01(\x03R\n" +
	"generation\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1b\n" +
	"\tinput_ids\x18\a \x03(\tR\binputIds\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x16\n" +
	"\x06result\x18\t \x01(\fR\x06result\x12\x1d\n" +
	"\n" +
	"error_code\x18\n" +
	" \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\f \x01(\fR\n" +
	"checkpoint\x12\x14\n" +
	"\x05usage\x18\r \x01(\fR\x05usage\x12'\n" +
	"\x0fidempotency_key\x18\x0e \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\rattempt_token\x18\x0f \x01(\tR\fattemptToken\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xab\x01\n" +
	"\x0eInstanceHealth\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12'\n" +
	"\x0factive_sessions\x18\x03 \x01(\x05R\x0eactiveSessions\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x05 \x01(\x01R\vmemoryUsage\"k\n" +
	"\vEventReport\x12?\n" +
	"\x06events\x18\x01 \x03(\v2'.agentscope.protocol.v1.SessionEventMsgR\x06events\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\"\x8d\x01\n" +
	"\x0eEventReportAck\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12H\n" +
	"\tcommitted\x18\x02 \x03(\v2*.agentscope.protocol.v1.SessionEventCursorR\tcommitted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"X\n" +
	"\x12SessionEventCursor\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rcommitted_seq\x18\x02 \x01(\x05R\fcommittedSeq\"\x91\x03\n" +
	"\x0fSessionEventMsg\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1f\n" +
	"\voccurred_at\x18\x04 \x01(\x03R\n" +
	"occurredAt\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1b\n" +
	"\ttool_name\x18\a \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"tool_input\x18\b \x01(\fR\ttoolInput\x12\x1f\n" +
	"\vtool_output\x18\t \x01(\tR\n" +
	"toolOutput\x12\x1b\n" +
	"\ttokens_in\x18\n" +
	" \x01(\x05R\btokensIn\x12\x1d\n" +
	"\n" +
	"tokens_out\x18\v \x01(\x05R\ttokensOut\x12\x1f\n" +
	"\vduration_ms\x18\f \x01(\x05R\n" +
	"durationMs\x12%\n" +
	"\x0eframework_meta\x18\r \x01(\fR\rframeworkMeta\"\xfd\x03\n" +
	"\rContextReport\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fcontext_hash\x18\x02 \x01(\tR\vcontextHash\x12\x1f\n" +
	"\vcaptured_at\x18\x03 \x01(\x03R\n" +
	"capturedAt\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12\x1a\n" +
	"\bmessages\x18\x05 \x01(\fR\bmessages\x12\x14\n" +
	"\x05tools\x18\x06 \x01(\fR\x05tools\x12!\n" +
	"\fis_compacted\x18\a \x01(\bR\visCompacted\x12-\n" +
	"\x12compaction_summary\x18\b \x01(\tR\x11compactionSummary\x124\n" +
	"\x16original_message_count\x18\t \x01(\x05R\x14originalMessageCount\x12!\n" +
	"\fcompacted_at\x18\n" +
	" \x01(\x03R\vcompactedAt\x12!\n" +
	"\ftotal_tokens\x18\v \x01(\x05R\vtotalTokens\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\f \x01(\x05R\tmaxTokens\x12\x1c\n" +
	"\tframework\x18\r \x01(\tR\tframework\x12'\n" +
	"\x0fframework_state\x18\x0e \x01(\fR\x0eframeworkState\"\xdc\x01\n" +
	"\x0fInventoryReport\x12B\n" +
	"\tsubagents\x18\x01 \x03(\v2$.agentscope.protocol.v1.SubagentInfoR\tsubagents\x12E\n" +
	"\n" +
	"workspaces\x18\x02 \x03(\v2%.agentscope.protocol.v1.WorkspaceInfoR\n" +
	"workspaces\x12>\n" +
	"\x06health\x18\x03 \x01(\v2&.agentscope.protocol.v1.InstanceHealthR\x06health\"\xde\x01\n" +
	"\fSubagentInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05tools\x18\x03 \x03(\tR\x05tools\x12%\n" +
	"\x0eworkspace_mode\x18\x04 \x01(\tR\rworkspaceMode\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12!\n" +
	"\finvoke_count\x18\x06 \x01(\x03R\vinvokeCount\x12&\n" +
	"\x0flast_invoked_at\x18\a \x01(\x03R\rlastInvokedAt\"s\n" +
	"\rWorkspaceInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\towner_ref\x18\x04 \x01(\tR\bownerRef\"\xbf\x04\n" +
	"\n" +
	"Downstream\x12J\n" +
	"\vconnect_ack\x18\n" +
	" \x01(\v2'.agentscope.protocol.v1.ConnectResponseH\x00R\n" +
	"connectAck\x12E\n" +
	"\vconfig_push\x18\v \x01(\v2\".agentscope.protocol.v1.ConfigPushH\x00R\n" +
	"configPush\x12I\n" +
	"\vsession_cmd\x18\f \x01(\v2&.agentscope.protocol.v1.SessionCommandH\x00R\n" +
	"sessionCmd\x12^\n" +
	"\x11execution_attempt\x18\r \x01(\v2/.agentscope.protocol.v1.ExecutionAttemptCommandH\x00R\x10executionAttempt\x12A\n" +
	"\theartbeat\x18\x0e \x01(\v2!.agentscope.protocol.v1.HeartbeatH\x00R\theartbeat\x12^\n" +
	"\x11conversation_turn\x18\x0f \x01(\v2/.agentscope.protocol.v1.ConversationTurnCommandH\x00R\x10conversationTurn\x12E\n" +
	"\tevent_ack\x18\x10 \x01(\v2&.agentscope.protocol.v1.EventReportAckH\x00R\beventAckB\t\n" +
	"\apayload\"\x86\x01\n" +
	"\x0fConnectResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x02 \x01(\tR\frejectReason\x122\n" +
	"\x15control_plane_version\x18\x03 \x01(\tR\x13controlPlaneVersion\"\x9f\x01\n" +
	"\n" +
	"ConfigPush\x12C\n" +
	"\vconfig_type\x18\x01 \x01(\x0e2\".agentscope.protocol.v1.ConfigTypeR\n" +
	"configType\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tresources\x18\x03 \x01(\fR\tresources\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\"a\n" +
	"\x0eSessionCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\"\xf3\x02\n" +
	"\x17ConversationTurnCommand\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x17\n" +
	"\aturn_id\x18\x03 \x01(\tR\x06turnId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x06 \x01(\tR\tbindingId\x12\x1f\n" +
	"\vinstance_id\x18\a \x01(\tR\n" +
	"instanceId\x12\x1e\n" +
	"\n" +
	"generation\x18\b \x01(\x03R\n" +
	"generation\x12\x14\n" +
	"\x05input\x18\t \x01(\fR\x05input\x12\x1a\n" +
	"\bdeadline\x18\n" +
	" \x01(\x03R\bdeadline\x12%\n" +
	"\x0ecorrelation_id\x18\v \x01(\tR\rcorrelationId\"\xd0\x02\n" +
	"\x16ConversationTurnReport\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x17\n" +
	"\aturn_id\x18\x03 \x01(\tR\x06turnId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"generation\x18\x05 \x01(\x03R\n" +
	"generation\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x03R\bsequence\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"error_code\x18\t \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\"\x8c\x03\n" +
	"\x17ExecutionAttemptCommand\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\"\n" +
	"\ragent_task_id\x18\x02 \x01(\tR\vagentTaskId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x1e\n" +
	"\n" +
	"generation\x18\x05 \x01(\x03R\n" +
	"generation\x12\x18\n" +
	"\acommand\x18\x06 \x01(\tR\acommand\x12\x1f\n" +
	"\vcontext_url\x18\a \x01(\tR\n" +
	"contextUrl\x12\x1d\n" +
	"\n" +
	"task_token\x18\b \x01(\tR\ttaskToken\x12#\n" +
	"\rattempt_token\x18\t \x01(\tR\fattemptToken\x12'\n" +
	"\x0fruntime_binding\x18\n" +
	" \x01(\fR\x0eruntimeBinding\x12\x18\n" +
	"\apayload\x18\v \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\f \x01(\x03R\ttimestamp*\x9e\x01\n" +
	"\n" +
	"ConfigType\x12\x1b\n" +
	"\x17CONFIG_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CONFIG_TYPE_AGENT\x10\x01\x12\x14\n" +
	"\x10CONFIG_TYPE_TOOL\x10\x02\x12\x15\n" +
	"\x11CONFIG_TYPE_SKILL\x10\x03\x12\x18\n" +
	"\x14CONFIG_TYPE_OVERRIDE\x10\x04\x12\x15\n" +
	"\x11CONFIG_TYPE_MODEL\x10\x052l\n" +
	"\x15AgentDataPlaneService\x12S\n" +
	"\aConnect\x12 .agentscope.protocol.v1.Upstream\x1a\".agentscope.protocol.v1.Downstream(\x010\x01Bj\n" +
	"\x1aio.agentscope.aistio.protoB\tAsdpProtoP\x01Z?github.com/agentscope/agentscope-go/control-plane/internal/asdpb\x06proto3"

var (
	file_internal_asdp_asdp_proto_rawDescOnce sync.Once
	file_internal_asdp_asdp_proto_rawDescData []byte
)

func file_internal_asdp_asdp_proto_rawDescGZIP() []byte {
	file_internal_asdp_asdp_proto_rawDescOnce.Do(func() {
		file_internal_asdp_asdp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_asdp_asdp_proto_rawDesc), len(file_internal_asdp_asdp_proto_rawDesc)))
	})
	return file_internal_asdp_asdp_proto_rawDescData
}

var file_internal_asdp_asdp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_asdp_asdp_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_internal_asdp_asdp_proto_goTypes = []any{
	(ConfigType)(0),                 // 0: agentscope.protocol.v1.ConfigType
	(*Upstream)(nil),                // 1: agentscope.protocol.v1.Upstream
	(*UpstreamMeta)(nil),            // 2: agentscope.protocol.v1.UpstreamMeta
	(*ConnectRequest)(nil),          // 3: agentscope.protocol.v1.ConnectRequest
	(*ConfigAck)(nil),               // 4: agentscope.protocol.v1.ConfigAck
	(*SessionReport)(nil),           // 5: agentscope.protocol.v1.SessionReport
	(*SessionSnapshot)(nil),         // 6: agentscope.protocol.v1.SessionSnapshot
	(*ExecutionAttemptReport)(nil),  // 7: agentscope.protocol.v1.ExecutionAttemptReport
	(*Heartbeat)(nil),               // 8: agentscope.protocol.v1.Heartbeat
	(*InstanceHealth)(nil),          // 9: agentscope.protocol.v1.InstanceHealth
	(*EventReport)(nil),             // 10: agentscope.protocol.v1.EventReport
	(*EventReportAck)(nil),          // 11: agentscope.protocol.v1.EventReportAck
	(*SessionEventCursor)(nil),      // 12: agentscope.protocol.v1.SessionEventCursor
	(*SessionEventMsg)(nil),         // 13: agentscope.protocol.v1.SessionEventMsg
	(*ContextReport)(nil),           // 14: agentscope.protocol.v1.ContextReport
	(*InventoryReport)(nil),         // 15: agentscope.protocol.v1.InventoryReport
	(*SubagentInfo)(nil),            // 16: agentscope.protocol.v1.SubagentInfo
	(*WorkspaceInfo)(nil),           // 17: agentscope.protocol.v1.WorkspaceInfo
	(*Downstream)(nil),              // 18: agentscope.protocol.v1.Downstream
	(*ConnectResponse)(nil),         // 19: agentscope.protocol.v1.ConnectResponse
	(*ConfigPush)(nil),              // 20: agentscope.protocol.v1.ConfigPush
	(*SessionCommand)(nil),          // 21: agentscope.protocol.v1.SessionCommand
	(*ConversationTurnCommand)(nil), // 22: agentscope.protocol.v1.ConversationTurnCommand
	(*ConversationTurnReport)(nil),  // 23: agentscope.protocol.v1.ConversationTurnReport
	(*ExecutionAttemptCommand)(nil), // 24: agentscope.protocol.v1.ExecutionAttemptCommand
}
var file_internal_asdp_asdp_proto_depIdxs = []int32{
	2,  // 0: agentscope.protocol.v1.Upstream.meta:type_name -> agentscope.protocol.v1.UpstreamMeta
	3,  // 1: agentscope.protocol.v1.Upstream.connect:type_name -> agentscope.protocol.v1.ConnectRequest
	4,  // 2: agentscope.protocol.v1.Upstream.config_ack:type_name -> agentscope.protocol.v1.ConfigAck
	5,  // 3: agentscope.protocol.v1.Upstream.session_report:type_name -> agentscope.protocol.v1.SessionReport
	7,  // 4: agentscope.protocol.v1.Upstream.execution_attempt:type_name -> agentscope.protocol.v1.ExecutionAttemptReport
	8,  // 5: agentscope.protocol.v1.Upstream.heartbeat:type_name -> agentscope.protocol.v1.Heartbeat
	10, // 6: agentscope.protocol.v1.Upstream.event_report:type_name -> agentscope.protocol.v1.EventReport
	14, // 7: agentscope.protocol.v1.Upstream.context_report:type_name -> agentscope.protocol.v1.ContextReport
	15, // 8: agentscope.protocol.v1.Upstream.inventory:type_name -> agentscope.protocol.v1.InventoryReport
	23, // 9: agentscope.protocol.v1.Upstream.conversation_turn:type_name -> agentscope.protocol.v1.ConversationTurnReport
	0,  // 10: agentscope.protocol.v1.ConfigAck.config_type:type_name -> agentscope.protocol.v1.ConfigType
	6,  // 11: agentscope.protocol.v1.SessionReport.sessions:type_name -> agentscope.protocol.v1.SessionSnapshot
	13, // 12: agentscope.protocol.v1.EventReport.events:type_name -> agentscope.protocol.v1.SessionEventMsg
	12, // 13: agentscope.protocol.v1.EventReportAck.committed:type_name -> agentscope.protocol.v1.SessionEventCursor
	16, // 14: agentscope.protocol.v1.InventoryReport.subagents:type_name -> agentscope.protocol.v1.SubagentInfo
	17, // 15: agentscope.protocol.v1.InventoryReport.workspaces:type_name -> agentscope.protocol.v1.WorkspaceInfo
	9,  // 16: agentscope.protocol.v1.InventoryReport.health:type_name -> agentscope.protocol.v1.InstanceHealth
	19, // 17: agentscope.protocol.v1.Downstream.connect_ack:type_name -> agentscope.protocol.v1.ConnectResponse
	20, // 18: agentscope.protocol.v1.Downstream.config_push:type_name -> agentscope.protocol.v1.ConfigPush
	21, // 19: agentscope.protocol.v1.Downstream.session_cmd:type_name -> agentscope.protocol.v1.SessionCommand
	24, // 20: agentscope.protocol.v1.Downstream.execution_attempt:type_name -> agentscope.protocol.v1.ExecutionAttemptCommand
	8,  // 21: agentscope.protocol.v1.Downstream.heartbeat:type_name -> agentscope.protocol.v1.Heartbeat
	22, // 22: agentscope.protocol.v1.Downstream.conversation_turn:type_name -> agentscope.protocol.v1.ConversationTurnCommand
	11, // 23: agentscope.protocol.v1.Downstream.event_ack:type_name -> agentscope.protocol.v1.EventReportAck
	0,  // 24: agentscope.protocol.v1.ConfigPush.config_type:type_name -> agentscope.protocol.v1.ConfigType
	1,  // 25: agentscope.protocol.v1.AgentDataPlaneService.Connect:input_type -> agentscope.protocol.v1.Upstream
	18, // 26: agentscope.protocol.v1.AgentDataPlaneService.Connect:output_type -> agentscope.protocol.v1.Downstream
	26, // [26:27] is the sub-list for method output_type
	25, // [25:26] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_internal_asdp_asdp_proto_init() }
func file_internal_asdp_asdp_proto_init() {
	if File_internal_asdp_asdp_proto != nil {
		return
	}
	file_internal_asdp_asdp_proto_msgTypes[0].OneofWrappers = []any{
		(*Upstream_Connect)(nil),
		(*Upstream_ConfigAck)(nil),
		(*Upstream_SessionReport)(nil),
		(*Upstream_ExecutionAttempt)(nil),
		(*Upstream_Heartbeat)(nil),
		(*Upstream_EventReport)(nil),
		(*Upstream_ContextReport)(nil),
		(*Upstream_Inventory)(nil),
		(*Upstream_ConversationTurn)(nil),
	}
	file_internal_asdp_asdp_proto_msgTypes[17].OneofWrappers = []any{
		(*Downstream_ConnectAck)(nil),
		(*Downstream_ConfigPush)(nil),
		(*Downstream_SessionCmd)(nil),
		(*Downstream_ExecutionAttempt)(nil),
		(*Downstream_Heartbeat)(nil),
		(*Downstream_ConversationTurn)(nil),
		(*Downstream_EventAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_asdp_asdp_proto_rawDesc), len(file_internal_asdp_asdp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_asdp_asdp_proto_goTypes,
		DependencyIndexes: file_internal_asdp_asdp_proto_depIdxs,
		EnumInfos:         file_internal_asdp_asdp_proto_enumTypes,
		MessageInfos:      file_internal_asdp_asdp_proto_msgTypes,
	}.Build()
	File_internal_asdp_asdp_proto = out.File
	file_internal_asdp_asdp_proto_goTypes = nil
	file_internal_asdp_asdp_proto_depIdxs = nil
}
